config/routes.rb
Rails.application.routes.draw do
  resources :alerts
  resources :buses
  resources :stops

  root 'welcome#index'

  match '/findBuses' => 'buses#findBuses', via: :post
  match '/findBuses' => 'buses#findBuses', via: :get

  get 'buses' =>  'buses#index'

end

app/models/alert.rb
class Alert < ActiveRecord::Base
end

app/models/bus.rb
require 'rubygems'
require 'httparty'
require "json"

class Bus < ActiveRecord::Base
	include HTTParty
	format :json

	def self.findStops(route)
		response = HTTParty.get('http://api.translink.ca/rttiapi/v1/buses?apikey=UeuMwgvJ7kQ2cgFuDMVr&routeNo='+route, :headers => { 'Content-Type' => 'application/json', 'Accept' => 'application/json'})

		response.each do |b|
			Bus.create(direction: b['Direction'], latitude: b['Latitude'], longitude: b['Longitude'], destination: b['Destination'], bid: b['VehicleNo'] )
		end
		
	end

	def self.parseLatLon(br)
	    tempLat = br.latitude
	    tempLon = br.longitude
	    arr = [tempLat, tempLon]
	    arr
  	end

  	def self.imgStr(arr)
    	"https://maps.googleapis.com/maps/api/staticmap?center=" + arr.first.to_s + "," + arr.last.to_s + "&zoom=14&size=800x800&markers=" + arr.first.to_s + "," + arr.last.to_s + "&sensor=false"
  	end




end

app/models/stop.rb
class Stop < ActiveRecord::Base
end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController
  before_action :set_alert, only: [:show, :edit, :update, :destroy]

  # GET /alerts
  # GET /alerts.json
  def index
    @alerts = Alert.all
  end

  # GET /alerts/1
  # GET /alerts/1.json
  def show
  end

  # GET /alerts/new
  def new
    @alert = Alert.new
  end

  # GET /alerts/1/edit
  def edit
  end

  # POST /alerts
  # POST /alerts.json
  def create
    @alert = Alert.new(alert_params)

    respond_to do |format|
      if @alert.save
        format.html { redirect_to @alert, notice: 'Alert was successfully created.' }
        format.json { render :show, status: :created, location: @alert }
      else
        format.html { render :new }
        format.json { render json: @alert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alerts/1
  # PATCH/PUT /alerts/1.json
  def update
    respond_to do |format|
      if @alert.update(alert_params)
        format.html { redirect_to @alert, notice: 'Alert was successfully updated.' }
        format.json { render :show, status: :ok, location: @alert }
      else
        format.html { render :edit }
        format.json { render json: @alert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alerts/1
  # DELETE /alerts/1.json
  def destroy
    @alert.destroy
    respond_to do |format|
      format.html { redirect_to alerts_url, notice: 'Alert was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alert
      @alert = Alert.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alert_params
      params.require(:alert).permit(:bus, :latitude, :longitude, :number)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/buses_controller.rb
class BusesController < ApplicationController
  before_action :set_bus, only: [:show, :edit, :update, :destroy]
  include BusesHelper


  # GET /buses
  # GET /buses.json
  def index
    @buses = Bus.all
  end

  # GET /buses/1
  # GET /buses/1.json
  def show
  end

  # GET /buses/new
  def new
    @bus = Bus.new
  end

  # GET /buses/1/edit
  def edit
  end

  #Show all buses found
  def findBuses
    Bus.delete_all
    route = params[:route]
    Bus.findStops(route)
    redirect_to buses_path
  end


  # POST /buses
  # POST /buses.json
  def create
    @bus = Bus.new(bus_params)

    respond_to do |format|
      if @bus.save
        format.html { redirect_to @bus, notice: 'Bus was successfully created.' }
        format.json { render :show, status: :created, location: @bus }
      else
        format.html { render :new }
        format.json { render json: @bus.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buses/1
  # PATCH/PUT /buses/1.json
  def update
    respond_to do |format|
      if @bus.update(bus_params)
        format.html { redirect_to @bus, notice: 'Bus was successfully updated.' }
        format.json { render :show, status: :ok, location: @bus }
      else
        format.html { render :edit }
        format.json { render json: @bus.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buses/1
  # DELETE /buses/1.json
  def destroy
    @bus.destroy
    respond_to do |format|
      format.html { redirect_to buses_url, notice: 'Bus was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bus
      @bus = Bus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bus_params
      params.require(:bus).permit(:destination, :latitude, :longitude, :direction)
    end
end

app/controllers/stops_controller.rb
class StopsController < ApplicationController
  before_action :set_stop, only: [:show, :edit, :update, :destroy]

  # GET /stops
  # GET /stops.json
  def index
    @stops = Stop.all
  end

  # GET /stops/1
  # GET /stops/1.json
  def show
  end

  def search_stop
    response = HTTParty.get('http://api.translink.ca/rttiapi/v1/routes/99?apikey=UeuMwgvJ7kQ2cgFuDMVr', :headers => { 'Content-Type' => 'application/json', 'Accept' => 'application/json'})
    body = JSON.parse(response.body)
  end

  # GET /stops/new
  def new
    @stop = Stop.new
  end

  # GET /stops/1/edit
  def edit
  end

  # POST /stops
  # POST /stops.json
  def create
    @stop = Stop.new(stop_params)

    respond_to do |format|
      if @stop.save
        format.html { redirect_to @stop, notice: 'Stop was successfully created.' }
        format.json { render :show, status: :created, location: @stop }
      else
        format.html { render :new }
        format.json { render json: @stop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stops/1
  # PATCH/PUT /stops/1.json
  def update
    respond_to do |format|
      if @stop.update(stop_params)
        format.html { redirect_to @stop, notice: 'Stop was successfully updated.' }
        format.json { render :show, status: :ok, location: @stop }
      else
        format.html { render :edit }
        format.json { render json: @stop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stops/1
  # DELETE /stops/1.json
  def destroy
    @stop.destroy
    respond_to do |format|
      format.html { redirect_to stops_url, notice: 'Stop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stop
      @stop = Stop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stop_params
      params.require(:stop).permit(:stopNumber, :onStreet, :atStreet, :lat, :lon)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

def index
end

end

app/helpers/alerts_helper.rb
module AlertsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buses_helper.rb
require "json"

module BusesHelper

end

app/helpers/stops_helper.rb
module StopsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/alerts/_form.html.erb
<%= form_for(@alert) do |f| %>
  <% if @alert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alert.errors.count, "error") %> prohibited this alert from being saved:</h2>

      <ul>
      <% @alert.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :bus %><br>
    <%= f.number_field :bus %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :number %><br>
    <%= f.text_field :number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/alerts/edit.html.erb
<h1>Editing Alert</h1>

<%= render 'form' %>

<%= link_to 'Show', @alert %> |
<%= link_to 'Back', alerts_path %>

app/views/alerts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Alerts</h1>

<table>
  <thead>
    <tr>
      <th>Bus</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alerts.each do |alert| %>
      <tr>
        <td><%= alert.bus %></td>
        <td><%= alert.latitude %></td>
        <td><%= alert.longitude %></td>
        <td><%= alert.number %></td>
        <td><%= link_to 'Show', alert %></td>
        <td><%= link_to 'Edit', edit_alert_path(alert) %></td>
        <td><%= link_to 'Destroy', alert, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alert', new_alert_path %>

app/views/alerts/new.html.erb
<h1>New Alert</h1>

<%= render 'form' %>

<%= link_to 'Back', alerts_path %>

app/views/alerts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bus:</strong>
  <%= @alert.bus %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @alert.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @alert.longitude %>
</p>

<p>
  <strong>Number:</strong>
  <%= @alert.number %>
</p>

<%= link_to 'Edit', edit_alert_path(@alert) %> |
<%= link_to 'Back', alerts_path %>

app/views/buses/_form.html.erb
<%= form_for(@bus) do |f| %>
  <% if @bus.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bus.errors.count, "error") %> prohibited this bus from being saved:</h2>

      <ul>
      <% @bus.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :destination %><br>
    <%= f.text_area :destination %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :direction %><br>
    <%= f.text_field :direction %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/buses/edit.html.erb
<h1>Editing Bus</h1>

<%= render 'form' %>

<%= link_to 'Show', @bus %> |
<%= link_to 'Back', buses_path %>

app/views/buses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Buses</h1>

<table>
  <thead>
    <tr>
      <th>Destination</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Direction</th>
      <th>Bus ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buses.each do |bus| %>
      <tr>
        <td><%= bus.destination %></td>
        <td><%= bus.latitude %></td>
        <td><%= bus.longitude %></td>
        <td><%= bus.direction %></td>
        <td><%= bus.bid %></td>
        <td><%= link_to 'Show', bus %></td>
        <td><%= link_to 'Edit', edit_bus_path(bus) %></td>
        <td><%= link_to 'Destroy', bus, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bus', new_bus_path %>

app/views/buses/new.html.erb
<h1>New Bus</h1>

<%= render 'form' %>

<%= link_to 'Back', buses_path %>

app/views/buses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Destination:</strong>
  <%= @bus.destination %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @bus.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @bus.longitude %>
</p>

<p>
  <strong>Direction:</strong>
  <%= @bus.direction %>
</p>

<p>
  <strong>Bus ID:</strong>
  <%= @bus.bid %>
</p>
<div class="input-group">
        <span class="input-group-btn">
          <button class="btn btn-default" type="button" onclick="codeAddress()">Create Alert!</button>
        </span>
        <form onsubmit="codeAddress(); return false">
          <input id="address" class="form-control" placeholder="Enter Address">
        </form>
</div><!-- /input-group --> 

<div class="col-xs-9">
      <html>
        <body>

          <% latLonArr = Bus.parseLatLon(@bus) %>
          <% html = Bus.imgStr(latLonArr) %>

          <% img_height = 400 %>
          
          <img src=<%= html %> alt="Lamp" width=<%= img_height.to_s %> height=<%= img_height.to_s %> >

        </body>
      </html>
</div>

<%= link_to 'Edit', edit_bus_path(@bus) %> |
<%= link_to 'Back', buses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RideTheBuzz</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/stops/_form.html.erb
<%= form_for(@stop) do |f| %>
  <% if @stop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stop.errors.count, "error") %> prohibited this stop from being saved:</h2>

      <ul>
      <% @stop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :stopNumber %><br>
    <%= f.number_field :stopNumber %>
  </div>
  <div class="field">
    <%= f.label :onStreet %><br>
    <%= f.text_area :onStreet %>
  </div>
  <div class="field">
    <%= f.label :atStreet %><br>
    <%= f.text_area :atStreet %>
  </div>
  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lon %><br>
    <%= f.text_field :lon %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stops/edit.html.erb
<h1>Editing Stop</h1>

<%= render 'form' %>

<%= link_to 'Show', @stop %> |
<%= link_to 'Back', stops_path %>

app/views/stops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Stops</h1>

<table>
  <thead>
    <tr>
      <th>Stopnumber</th>
      <th>Onstreet</th>
      <th>Atstreet</th>
      <th>Lat</th>
      <th>Lon</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stops.each do |stop| %>
      <tr>
        <td><%= stop.stopNumber %></td>
        <td><%= stop.onStreet %></td>
        <td><%= stop.atStreet %></td>
        <td><%= stop.lat %></td>
        <td><%= stop.lon %></td>
        <td><%= link_to 'Show', stop %></td>
        <td><%= link_to 'Edit', edit_stop_path(stop) %></td>
        <td><%= link_to 'Destroy', stop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stop', new_stop_path %>

app/views/stops/new.html.erb
<h1>New Stop</h1>

<%= render 'form' %>

<%= link_to 'Back', stops_path %>

app/views/stops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Stopnumber:</strong>
  <%= @stop.stopNumber %>
</p>

<p>
  <strong>Onstreet:</strong>
  <%= @stop.onStreet %>
</p>

<p>
  <strong>Atstreet:</strong>
  <%= @stop.atStreet %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @stop.lat %>
</p>

<p>
  <strong>Lon:</strong>
  <%= @stop.lon %>
</p>

<div class="col-xs-9">
      <html>
        <body>

          <% latLonArr = Bus.parseLatLon(@bus) %>
          <% html = Bus.imgStr(latLonArr) %>

          <% img_height = 600 %>
          
          <img src=<%= html %> alt="Lamp" width=<%= img_height.to_s %> height=<%= img_height.to_s %> >

        </body>
      </html>
    </div>

<%= link_to 'Edit', edit_stop_path(@stop) %> |
<%= link_to 'Back', stops_path %>

app/views/welcome/index.html.erb
<h1>Ride da buzz</h1>

<h2>Please enter your route</h2>

<%= form_tag("/findBuses", method: "get") do %>
  <%= label_tag(:route, "Search for:") %>
  <%= text_field_tag(:route) %>
  <%= submit_tag("Search") %>
<% end %>